spring:
    jpa:
    hibernate.ddl-auto: none
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    datasource:
      url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true
      username: root
      password: jhona_mysql
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher